### PR TITLE
1.2.5.4. ‘__main__’ and module loading

### PR DESCRIPTION
**Pull request by prajwel**
this section had a small issue with In [12]. I have removed the line.

### CODE REVIEW

**Comment by pdebuyl** [comment]
Hi @prajwel 

Thank you for the feedback! The repeat call to `import` is made on purpose, to show that the module is not reloaded.

Did you have an error while testing the code? If so, could you provide the full traceback?

Regards,

Pierre

**Comment by prajwel** [comment]
Oh, sorry, I thought it was a mistake. I should have tested it before creating the pull request.

**Comment by pdebuyl** [comment]
No worry, we rely on direct testing so feedback is always welcome!

**Comment by prajwel** [comment]
Maybe a newline might make it less confusing after the second import?

**Pull request closed without merging**
