### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by caot**
added plt.show()

### CODE REVIEW

**Comment by vahtras** [comment]
Thanks! I principle you are correct, but there are numerous other places in these lecture notes that a similar change could be motivated leading to a lot of extra text and code repetition. This aspect is well described in the matplotlib introduction. Furthermore, these days it is probably more common to copy code snippets into the Jupyter notebook, so you may not even always want to have the plt.show() in there. I will leave this open, if someone else wants to comment.

**Comment by pdebuyl** [comment]
Should we have a "how to use these lecture notes" section?

**Comment by GaelVaroquaux** [comment]
> Should we have a "how to use these lecture notes" section?

Yes, but I don't think that we should write it now: soon there will be a
new sphinx-gallery release with binder integration, and this will be a
big deal.

**Comment by GaelVaroquaux** [comment]
> Great :-) Let us keep in mind that binder has downtime and that we should
> remain "what if binder is down" friendly :-)

Totally

> BTW, I am not sure I understand the scope: would all docstrings be concerned or
> only the examples that are currently managed by sphinx-gallery?

Only the examples managed by sphinx-gallery for now.

**Pull request closed without merging**
