### PR TITLE
Fix Python version inconsistencies in Travis

### PR DESCRIPTION
**Pull request by vahtras**
follow http://conda.pydata.org/docs/travis.html

### CODE REVIEW

**Comment by lesteve** [comment]
FWIW we generally use different versions of dependencies for python 2 and 3, in order to test on a wider range of versions, but that's fine for now.

**Comment by lesteve** [comment]
Your change actually bit me for the thing I was working on (CircleCI support), I'll probably revert some of it at one point if you don't mind.

**Comment by GaelVaroquaux** [comment]
> FWIW we generally use different versions of dependencies for python 2
> and 3, in order to test on a wider range of versions, but that's fine
> for now.

The problem is that there are so many backward incompatible changes in
the scipy ecosystem that it's actually not possible to have the full
scipy lecture notes running on too many versions of the packages.

**Comment by vahtras** [comment]
Sorry, next time I will not be so fast merging my own PR ;-)

**Comment by GaelVaroquaux** [comment]
> Sorry, next time I will not be so fast merging my own PR ;-)

What was your motivation behind making these changes? I don't remember
things being broken.

**Comment by vahtras** [comment]
Well there was some strange output in the Travis logs. The Python 3 test
had some reference to Python 2.7. What really made me look there in the
first place is that some tests fail locally with newer versions of scipy.

**Comment by lesteve** [comment]
> Sorry, next time I will not be so fast merging my own PR ;-)

No worries, for the record I don't think the Python 3.4 build is actually testing Python 2.7 ... Have a look at
https://travis-ci.org/scipy-lectures/scipy-lecture-notes/jobs/155594156#L563

**Comment by lesteve** [comment]
> No worries, for the record I think the Python 3.4 build is actually testing Python 2.7 ...
I opened #264 to fix this.

**Pull request merged**
