### PR TITLE
Added Pierre de Buyl in authors

### PR DESCRIPTION
**Pull request by rougier**
See #335

### CODE REVIEW

**Comment by gertingold** [comment]
Just a tiny detail, but it seems to me that the spacing of authors in the third line is very uneven. In other words, the space around the dot between Pierre and Ralf is much smaller than around the dot between André and Zbigniew.

**Comment by rougier** [comment]
I'll check

**Comment by gertingold** [comment]
Thanks. And sorry for being so picky about such a small detail.

**Comment by rougier** [comment]
Thanks for having spotted it. I'm also quite picky about details actually.

**Comment by GaelVaroquaux** [comment]
LGTM. Merging. Thanks

**Comment by pdebuyl** [comment]
Thanks @rougier , I appreciate :-)

**Pull request merged**
