### PR TITLE
Fix for the PDF cover

### PR DESCRIPTION
**Pull request by rougier**
Small fix for the cover that uses `pdfpages` instead of `includegraphics`.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
When I try to build your PR, I get the following LaTeX error:
<pre>
! LaTeX Error: Option clash for package graphicx.
</pre>
Are you not getting it? And if so, do you have any idea why I am getting it?

**Comment by rougier** [comment]
Yes, same here. I'll try to find a solution

**Comment by rougier** [comment]
Should work now.

**Comment by GaelVaroquaux** [comment]
Works fine. Merging.

**Pull request merged**
