### PR TITLE
Conversion to sphinx gallery

### PR DESCRIPTION
**Pull request by gertingold**
This PR contains a partial conversion to Sphinx gallery. It is set up already for some of the example directories but some work remains to be done.

### CODE REVIEW

**Comment by gertingold** [comment]
Now, a first version with Sphinx gallery is completed. Some tweaking might still be necessary, but basically it seems to work. Open issues include:

-  Should the example directories be scattered as they are right now or should they be brought together in one example tree?
-  In order for the presentation of the galleries to work, the `div.body div.figure` had to be removed from `nature.css_t` (thanks to @Titan-C) for figuring this out. There might be side effects of this change. Therefore, the corresponding code has not been removed but just commented out.
-  Appropriate links to the gallery need to be inserted into the webpage of the Scipy lecture notes.

**Comment by GaelVaroquaux** [comment]
Congratulations! Could you rebase on master (if you don't know how to do
this, I can help you). The reason is that it will turn on circleCI on
your PR, and hence everybody can inspect the resulting html.

>   • Should the example directories be scattered as they are right now or should
>     they be brought together in one example tree?

I think that they should be scattered. It helps having each chapter quite
self contained.

>   • In order for the presentation of the galleries to work, the div.body
>     div.figure had to be removed from nature.css_t (thanks to @Titan-C) for
>     figuring this out. There might be side effects of this change. Therefore,
>     the corresponding code has not been removed but just commented out.

I'll look at this.

>   • Appropriate links to the gallery need to be inserted into the webpage of
>     the Scipy lecture notes.

This is a great new functionality. Maybe we should merge before, in the
spirit of small incremental changes, rather than shooting for the moon. I
am all for rejoicing early, and rejoicing again later.

**Comment by GaelVaroquaux** [comment]
> Congratulations! Could you rebase on master

This PR would actually make testing on CircleCI much much easier. I am
working on such testing currently. So I'll work on your PR right now, to
try to left the last small technical hurdles to merging.

**Comment by gertingold** [comment]
I just did a rebase (hopefully correctly...). Of course, I agree to proceed in small steps. For the moment, sphinx gallery just provides a different way to produce the figures, so that the reader should not really see a difference, unless the change to the css file has side effects. We should make sure that on this level, everything is fine before proceeding. By the way, I have not yet removed matplotlibs gen_rst.

**Comment by gertingold** [comment]
It looks like circle ci does not know yet about sphinx-gallery, so its tests are failing. Travis ci seems to be happy.

**Comment by GaelVaroquaux** [comment]
> I just did a rebase (hopefully correctly...).

> Of course, I agree to proceed in small steps. For the moment, sphinx
> gallery just provides a different way to produce the figures, so that
> the reader should not really see a difference,

Yes. For now, it's mostly internal.

CircleCI fails because we need to add sphinx-gallery to circleCI. I'll do
this on my branch.

> unless the change to the css file has side effects.

Once CircleCI builds, I'll check that.

> By the way, I have not yet removed matplotlibs gen_rst.

OK, we'll do that after.

**Comment by GaelVaroquaux** [comment]
I fixed the circleCI rendering. The resulting build is visible on:
https://7-1375598-gh.circle-artifacts.com/0//home/ubuntu/scipy-lecture-notes/build/html/index.html

**Comment by gertingold** [comment]
Thanks!  Not in all sections example directories are properly set up yet. Should that be the next step?

**Comment by GaelVaroquaux** [comment]
> Thanks! Not in all sections example directories are properly set up yet.

Hum, I don't understand the comment? Do you mean that sphinx-gallery
renders only a few of the examples?

> Should that be the next step?

If I have understood correctly, yes, that would be the next step.

If yo want, I can make a PR to your PR, and that way you can merge, and
keep working on your PR.

**Comment by gertingold** [comment]
No, examples are built correctly. But e.g. `packages/scikit-learn` does not contain an
`examples` directory yet. I also just realized that I missed directories with an `examples` directory, e.g. `packages/3d-plotting`. So, if you make a PR to my PR, I will continue to work on this, either tomorrow or more likely after my arrival in Brazil.

**Comment by GaelVaroquaux** [comment]
> No, examples are built correctly. But e.g. packages/scikit-learn does
> not contain an examples directory yet.

OK. I'll look at that in parallel. I don't really like the changes to the
CSS, as they will break other layouts.

> I also just realized that I missed directories with an examples
> directory, e.g. packages/3d-plotting. So, if you make a PR to my PR, I
> will continue to work on this, either tomorrow or more likely after my
> arrival in Brazil.

OK, I'll make a PR in a minute. We can work in parallel, as CSS work is
different.

**Comment by GaelVaroquaux** [comment]
> > So, if you make a PR to my PR, I will continue to work on this,
> > either tomorrow or more likely after my arrival in Brazil.

> OK, I'll make a PR in a minute. We can work in parallel, as CSS work is
> different.

Hum, I am sorry, I am failing to do a PR: you don't appear as a fork of
sphinx-gallery. I am not sure what the problem is.

**Comment by gertingold** [comment]
I have indeed not forked sphinx-gallery. But why is that needed at this point. Probably I am missing something here.

**Comment by GaelVaroquaux** [comment]
> I have indeed not forked sphinx-gallery. But why is that needed at this point.
> Probably I am missing something here.

No, sorry, it's in the scipy-lecture-notes fork that I am not finding
you. Maybe it's because you created your fork from a child of the main
repo. I don't know why. Anyhow, it's not a big deal, if you can fix the
problem that you have found on your PR, it's fine.

**Comment by gertingold** [comment]
Strange,  I had forked from  scipy-lectures/scipy-lecture-notes. Anyway, we can proceed in the way you suggested.

**Comment by GaelVaroquaux** [comment]
> Strange, I had forked from scipy-lectures/scipy-lecture-notes.

Maybe it's a bug of github. Don't worry about it.

**Comment by GaelVaroquaux** [comment]
Closing, as the work was finished in #257

**Pull request closed without merging**
