### PR TITLE
Added module initialization code for python 3

### PR DESCRIPTION
**Pull request by rougier**
I've been testing this code during a lesson and the module initialization code is for python 2. I added the code for python3 and make it the default.

Maybe a test from at least another person would be good before merge.

### CODE REVIEW

**Comment by rougier** [comment]
ping !

**Comment by rougier** [comment]
ping !

**Comment by pdebuyl** [comment]
From http://python3porting.com/cextensions.html it is not too difficult to make this 2/3 compatible. See https://github.com/pdebuyl/scipy-lecture-notes/tree/c_python_fix

**Comment by rougier** [comment]
Thanks for the pointer, I will make the change.

**Comment by pdebuyl** [comment]
You can just cherry-pick or merge my branch :-) Is an update of the text at http://www.scipy-lectures.org/advanced/interfacing_with_c/interfacing_with_c.html needed?

**Comment by rougier** [comment]
Didn't realize you fixed it. Maybe even easier for you to make a PR, no ?

**Comment by pdebuyl** [comment]
Well, there's already a PR with a discussion. Solutions:
1. you make the PR editable and I push to your branch (git/github related discussions *do* sound weird)
2. you cherry-pick/merge my fork of your PR :-)

**Comment by pdebuyl** [comment]
Fixed by #331 instead, closing.

**Pull request closed without merging**
