### PR TITLE
Minor updates to the articles on NumPy

### PR DESCRIPTION
**Pull request by rossbar**
First off, thanks so much to the authors/contributors of the SLN - they are a great resource for learning & illustrating the features of the scientific Python ecosystem!

A few minor changes from a recent re-read of the NumPy articles (intro & advanced):

 * A wording suggestion (indexes->indices for consistency with the rest of the document)
 * Convert instances of `str(arr.data)` to `bytes(arr.data)` when used to illustrate the contents of the `data` attribute of arrays
 * Explicitly convert a couple instances of floats in scientific notation -> int so they are valid input to `np.zeros`

### CODE REVIEW

**Comment by pdebuyl** [comment]
Thank you for this contribution and for the encouraging comments!

Regarding the changes to bytes, it should be possible to remove the "+SKIP" doctest options here. They were added during the Python 2 to Python 3 transition because we did not find a way to pass the tests otherwise. We can now remove un-necessary SKIP directives as they reduce the automated testings of our notes. Could you test that? (`make test` will run the test on the whole set of files and `pytest advanced/advanced_numpy/index.rst` will run only the current file, from the root of the repository so that it can find the data files for some examples).

**Comment by rossbar** [comment]
> it should be possible to remove the "+SKIP" doctest options here.

This was a great suggestion that led to an interesting discovery. Though not well-documented, it seems that the `bytes` built-in actually returns the bytes object in C-order by default, so it is not at all suitable for illustrating memory layout as I had originally intended. FWIW, this is not mentioned anywhere in the `bytes` documentation itself, but can be inferred from the [`memoryview.tobytes` docs](https://docs.python.org/3/library/stdtypes.html#memoryview.tobytes).

To get around this limitation, I switched to the `tobytes(order='A')`, which preserves the ordering of the underlying memory. LMK if this change is okay, or if further changes are warranted (e.g. a note about `bytes` not preserving memory order?).

**Comment by pdebuyl** [comment]
It took me some time to re-figure out what you found out :-) A note would be welcome, for instance in the section "C and Fortran order".

**Comment by rossbar** [comment]
Okay, note added on `bytes()` vs. `ndarray.tobytes` for inspecting memory layout in 436d7de

**Comment by pdebuyl** [comment]
Thank you very much for the continued updates on this! Merging :-)

**Pull request merged**
