### PR TITLE
Sphinx gallery WIP - close #138

### LINKED ISSUE #138: Use sphinx-gallery
We can throw away our gen_rst.py and use sphinx gallery.

Once this is done, we can use it's cool features, like the fact that you can have multiple sub gallery, and the notebook-style examples.

### PR DESCRIPTION
**Pull request by djarecka**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
@djarecka : Tell me what your plan is for this work: do you want to keep going at it; do you need help; or do you need someone to take over?

**Comment by djarecka** [comment]
@GaelVaroquaux : I was hoping to have some time this week but finally didn't. I really doubt that will have time this month to learn Sphinx-gallery, so it might be much faster if someone takes it over.

**Comment by GaelVaroquaux** [comment]
@djarecka : right now I am also tied down by a few things (some work related, some open source related). So I won't have time to personally take this up. Let's see if someone does. Whoever get there first will have a go at this.

**Comment by GaelVaroquaux** [comment]
Closing, as superseeded by #257

**Pull request closed without merging**
