### PR TITLE
Matplotlib typo fixes

### PR DESCRIPTION
**Pull request by Shoeboxam**
Please note that the paths to files under auto_examples have also been edited. The filenames on the server would need to be modified to reflect these changes. It seems these files are not hosted here on the git repo, so I cannot make those fixes.

### CODE REVIEW

**Comment by gertingold** [comment]
The changes seem fine to me. In particular, I can build HTML without any problems and I don't know why CircleCI failed.

**Comment by GaelVaroquaux** [comment]
I've restarted circle. Let's see what it gives.

**Comment by gertingold** [comment]
Thanks for your contribution

**Comment by GaelVaroquaux** [comment]
Indeed, circle passed. Thanks!

**Pull request merged**
