### PR TITLE
Include Visual Studio Code to intro

### PR DESCRIPTION
**Pull request by Hofer-Julian**
It offers excellent python and anaconda support and I think it should be included to the list

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
LGTM, +1 for merge when CI has ran.

**Comment by pdebuyl** [comment]
What about linking to the Python language page directly?

https://code.visualstudio.com/docs/languages/python

**Comment by Hofer-Julian** [comment]
@pdebuyl True, that's better

**Comment by GaelVaroquaux** [comment]
Thanks. Merging!

**Pull request merged**
