### PR TITLE
Add documentation generation on CircleCI

### LINKED ISSUE #244: Set up circle-CI to render docs and examples
The best option is to adapt that of nilearn.

Maybe @lesteve can help with that?

### PR DESCRIPTION
**Pull request by lesteve**
Some modifications necessary in continuous_integration/install.sh to make it compatible with both Travis and CircleCI.

Also for now tests are not run on CircleCI because there are plenty of errors I don't understand.

Fixes #244.

### CODE REVIEW

**Comment by lesteve** [comment]
Somebody with the necessary admin rights will need to add the scipy-lectures/scipy-lecture-notes project to CircleCI.

**Comment by GaelVaroquaux** [comment]
> Also for now tests are not run on CircleCI because there are plenty of
> errors I don't understand.

Are you using the same exact versions? It's quite touchy.

**Comment by lesteve** [comment]
> Are you using the same exact versions? It's quite touchy.

In principle it should, I copied the versions from .travis.yml.

**Comment by GaelVaroquaux** [comment]
> In principle it should, I copied the versions from .travis.yml.

I'll have a look ASAP.

**Comment by lesteve** [comment]
FYI, the documentation built by CircleCI on my branch:
https://27-66703500-gh.circle-artifacts.com/0//home/ubuntu/scipy-lecture-notes/build/html/index.html

**Comment by lesteve** [comment]
> I'll have a look ASAP.

No rush, I'll try to investigate a bit more as well.

**Comment by lesteve** [comment]
Hmmm it seems to work fine on my laptop, not sure why I had problems on CircleCI

**Comment by lesteve** [comment]
FWIW, a CircleCI build with errors:
https://circleci.com/gh/lesteve/scipy-lecture-notes/28

**Comment by emmanuelle** [comment]
@lesteve what is the interest of using CircleCI in addition to Travis?

**Comment by GaelVaroquaux** [comment]
> @lesteve what is the interest of using CircleCI in addition to Travis?

Generating docs and exposing them via the "artifacts" mechanism of
CircleCI.

**Comment by GaelVaroquaux** [comment]
> @lesteve what is the interest of using CircleCI in addition to Travis?

I had a look by sshing into a CircleCI instance. Something in the conda
install/conda environment is not behaving properly and the nosetests that
is used in circle is the systems.

As we don't need this to work, I am not very much interested in pursuing
this. Let's focus on getting the build of the html to work.

PS: IMHO, our build scripts are way too complicated. It's tricky shell.
Noone likes debugging these things.

**Comment by lesteve** [comment]
> As we don't need this to work, I am not very much interested in pursuing this. Let's focus on getting the build of the html to work. 

For the record the reason the conda environment was not picked up is that each command in CircleCI is executed in a separate shell, which is easy to forget when you are used to Travis ...

From https://circleci.com/docs/configuration/#phases
> Each command is run in a separate shell. As such, they do not share an environment with their predecessors, so be aware that export foo=bar in particular does not work. If you’d like to set an environment variable globally, you can specify them in the Machine configuration section, described below.

**Pull request merged**
