### PR TITLE
Replace Fedora build instructions with generic ones

### PR DESCRIPTION
**Pull request by pdebuyl**
Remove the Fedora build instructions. Nobody in the team currently uses
Fedora and can check the instructions.

Provide generic instructions based on pip instead.

### CODE REVIEW

**Comment by gertingold** [comment]
Your recipe fails for me in the step installing scikit-image

    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-CaXNEe/scikit-image/skimage/morphology/_skeletonize_3d_cy.pyx.in'

**Comment by pdebuyl** [comment]
Well, the version of scikit-image that we have pinned for conda has a configuration bug. One can use scikit-image 0.13 instead (this is what I do) but then the conda-mumbo-jumbo and the generic instructions are out of sync. There is probably no way out of it until we update scikit-image :-/

**Comment by gertingold** [comment]
What would break if we were to move to 0.13?

**Comment by pdebuyl** [comment]
I build with 0.13 on my computer. I filed a PR to test the CI with 0.13

**Comment by gertingold** [comment]
The only problem I see with this approach is that if somebody needs a different version of a package for some other project, there will be conflicts.

**Comment by pdebuyl** [comment]
At this point, we should include virtual environments in the instructions. That becomes too much in my opinion. The current situation is quite good: we have a working CI and we can get working instructions for, I suppose, the most common use cases. I admit that I run with globally installed packages and typically I have 3 to 5 docstring errors from the tests and the html builds fine.

**Pull request merged**
