### PR TITLE
Matplotlib: maintenance and style

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Update the matplotlib chapter:

- Reference jupyter in addition to IPython
- Many small style changes (clear floats to look better on small screens, integrate the gallery, put hints after question, use hlist)

### CODE REVIEW

**Comment by rougier** [comment]
if the code

```
.. raw:: html

   <div style="clear: both"></div>
```

is used a lot throughout the book, maybe we can use some [substitution definition](http://docutils.sourceforge.net/docs/ref/rst/directives.html#directives-for-substitution-definitions) such that we can write `|clear|`.

I personally use the `----` to clear because I never use the horizontal line.

**Comment by GaelVaroquaux** [comment]
@rougier : done. Thanks!

**Comment by GaelVaroquaux** [comment]
@rougier : are you OK with these changes? Should I merge?

**Comment by GaelVaroquaux** [comment]
Merged. Thanks @rougier for the review.

**Pull request merged**
